# File: pubspec.yaml
# Berisi konfigurasi proyek Flutter, termasuk dependensi, aset, dan pengaturan lingkungan.
# Digunakan untuk mengelola paket dan sumber daya aplikasi.

# Nama proyek
name: flutter_laundry_app
# Deskripsi proyek
description: "A new Flutter project."
# Menentukan bahwa proyek ini tidak akan dipublikasikan ke pub.dev
publish_to: 'none'
# Versi aplikasi
version: 1.0.0+1

# Lingkungan SDK yang didukung
environment:
  sdk: ^3.5.4 # Versi minimum SDK Flutter

# Dependensi aplikasi
dependencies:
  flutter:
    sdk: flutter # Framework Flutter
  firebase_core: ^3.12.0 # Inti Firebase untuk inisialisasi
  firebase_auth: ^5.1.4 # Autentikasi Firebase
  cloud_firestore: ^5.6.4 # Database Firestore untuk penyimpanan data
  firebase_storage: ^12.4.4 # Penyimpanan Firebase untuk file
  flutter_riverpod: ^2.6.1 # Manajemen state menggunakan Riverpod
  go_router: ^14.8.0 # Navigasi dan routing
  flutter_svg: ^2.0.17 # Dukungan untuk file SVG
  internet_connection_checker: ^3.0.1 # Pemeriksa koneksi internet
  dartz: ^0.10.1 # Utilitas untuk pemrograman fungsional
  tflite_flutter:
    path: D:/Kuliah/Semester 6/aplikasi berbasis platform/tubes1/tflite_flutter-0.11.0 # TensorFlow Lite untuk model ML
  cupertino_icons: ^1.0.8 # Ikon gaya Cupertino
  equatable: ^2.0.7 # Membantu perbandingan objek
  intl: ^0.20.2 # Format internasional untuk tanggal dan angka
  permission_handler: ^11.4.0 # Mengelola izin perangkat
  firebase_app_check: ^0.3.2+4 # Keamanan aplikasi Firebase
  logging: ^1.2.0 # Pencatatan log aplikasi

# Dependensi untuk pengembangan dan pengujian
dev_dependencies:
  flutter_test:
    sdk: flutter # Pengujian unit dan widget
  flutter_lints: ^5.0.0 # Aturan linter untuk kode Flutter

# Konfigurasi Flutter
flutter:
  uses-material-design: true # Menggunakan desain material
  # Daftar aset yang digunakan dalam aplikasi
  assets:
    - assets/svg/ # Folder untuk file SVG
    - assets/laundry_completion_model/laundry_completion_model.tflite # Model ML untuk prediksi waktu laundry