name: flutter_laundry_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.4
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  flutter_svg: ^2.0.17
  internet_connection_checker: ^3.0.1
  dartz: ^0.10.1
  tflite_flutter:
    path: D:/Kuliah/Semester 6/aplikasi berbasis platform/tubes1/tflite_flutter-0.11.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  intl: ^0.20.2
  permission_handler: ^11.4.0
  firebase_app_check: ^0.3.2+4
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/laundry_completion_model/laundry_completion_model.tflite